# cogs/memory/vector_store_interface.py

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import uuid

@dataclass
class MemoryFragment:
    """
    Represents a single fragment of episodic memory, ready for storage and retrieval.
    This structure separates the human-readable summary from the machine-searchable query key.
    """
    content: str  # The human-readable summary of the memory, generated by an LLM.
    query_key: str  # A keyword-rich string for vectorization, generated by an LLM.
    
    metadata: Dict[str, Any] = field(default_factory=dict)
    """
    A rich dictionary of metadata for filtering and context.
    Expected keys include:
    - fragment_id: str (UUID)
    - source_message_ids: List[str]
    - jump_url: str (URL to the primary source message)
    - author_id: str
    - channel_id: str
    - guild_id: str
    - timestamp: float (UTC timestamp)
    - reactions_json: str (JSON string of reaction data)
    """

    def __post_init__(self):
        # Ensure a unique ID for every fragment.
        if "fragment_id" not in self.metadata:
            self.metadata["fragment_id"] = str(uuid.uuid4())

class VectorStoreInterface(ABC):
    """
    Abstract Base Class for vector store implementations.
    Defines the standard interface for adding and searching episodic memories.
    """

    @abstractmethod
    async def add_memories(self, memories: List[MemoryFragment]) -> None:
        """
        Adds a list of memory fragments to the vector store.

        Args:
            memories: A list of MemoryFragment objects to be added.
        """
        pass

    @abstractmethod
    async def search_memories(
        self,
        query_text: str,
        user_id: Optional[str] = None,
        channel_id: Optional[str] = None,
        k: int = 5
    ) -> List[MemoryFragment]:
        """
        Searches for relevant memory fragments based on a query.

        Args:
            query_text: The text to search for.
            user_id: Optional user ID to filter memories by author.
            channel_id: Optional channel ID to filter memories.
            k: The number of results to return.

        Returns:
            A list of relevant MemoryFragment objects.
        """
        pass